language: nix
script: nix-build release.nix
matrix:
  include:
    - os: linux
      script: nix-build release.nix -A build.x86_64-linux
    - os: osx
      script: nix-build release.nix -A build.x86_64-darwin
